# .travis.yml
#
# YAML configuration file for the continuous integration platform "Travis CI".
#
# Author: Florian Wolters <wolters.fl@gmail.com>
#
# Copyright Florian Wolters (http://blog.florianwolters.de) 2014 - 2015.
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

language: cpp

compiler:
  - clang
  - gcc

before_install:
  # Add the "Ubuntu" Personal Package Archive (PPA) hosting newer upstream
  # versions as an Advanced Packaging Tool (APT) repository.
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # Add the (unoffical) "CMake" PPA as an APT repository.
  - sudo add-apt-repository -y ppa:kalakris/cmake

  # Add the official "Clang" website as an APT repository.
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main'; fi
  # Retrieve the archive signature for Clang.
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -

  # Re-synchronize the package index files from their sources.
  - sudo apt-get update -qq

install:
  # Install "CMake".
  - sudo apt-get install -qq cmake

  # Install "GNU Standard C++ Library".
  - sudo apt-get install libstdc++-4.9-dev

  # Install "GNU Compiler Collection (GCC)".
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.9; export CXX="g++-4.9" CC="gcc-4.9"; fi

  # Install "Clang".
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install clang-3.5; export CXX="clang++-3.5" CC="clang"; fi

  # Install "Google Test".
  - sudo apt-get install libgtest-dev

  # Build "Google Test".
  - cd /usr/src/gtest
  - sudo mkdir build
  - cd build
  - sudo cmake ..
  - sudo make
  - sudo mv libgtest* /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"

before_script:
  - mkdir build
  - cd build

  # Configure the project.
  - cmake ..

script:
  - cmake --version
  - $CXX --version
  - make --version

  # Build the project.
  - cmake --build .

  # Test the project.
  - ctest -V

notifications:
  email:
    on_success: change
    on_failure: always
