# .travis.yml
#
# YAML configuration file for the continuous integration platform "Travis CI".
#
# Copyright Florian Wolters 2014 (http://blog.florianwolters.de).
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; export CXX="g++-4.8" CC="gcc-4.8"; fi
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - wget http://www.biicode.com/downloads/latest/ubuntu64
  - mv ubuntu64 bii-ubuntu64.deb
  - (sudo dpkg -i bii-ubuntu64.deb) && sudo apt-get -f install
  - rm bii-ubuntu64.deb
  - wget http://www.cmake.org/files/v3.1/cmake-3.1.0.tar.gz
  - tar -xzf cmake-3.1.0.tar.gz
  - sudo cp -fR cmake-3.1.0/* /usr
  - rm -rf cmake-3.1.0
  - rm cmake-3.1.0.tar.gz

script:
  - cmake --version
  - bii init uncopyable
  - mkdir -p ./uncopyable/blocks/florianwolters/uncopyable
  - mv !(uncopyable) ./uncopyable/blocks/florianwolters/uncopyable
  - cd uncopyable
  - bii find -um
  - bii cpp:build

after_success:
- bii user florianwolters -p $BII_PASSWORD
- bii publish

notifications:
  email:
    on_success: change
    on_failure: always
